import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderContents from "@/components/HeaderContents";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${inter.className} relative`}>
        <HeaderContents />

        {children}
      </body>
    </html>
  );
}
